name: Send requests to GBI
env:
    GBIF_USER: ${{ secrets.GBIF_USER }}
    GBIF_EMAIL: ${{ secrets.GBIF_EMAIL }}
    GBIF_PWD: ${{ secrets.GBIF_PWD }}
on:
  schedule:
    - cron:  '00 01 24 * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Install requirements and jq
      run: |-
        pip install -r requirements.txt
        wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
        mv jq tmp/
        chmod +x tmp/jq
    - name: Send json request to gbif 
      run: |-
        ./gbif_apicall.sh
        cat query.json
        cat tmp/gbifcurlresponse.txt
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
